# see https://github.com/actions/labeler


api-change:
  - changed-files:
      - any-glob-to-any-file: "**/*.api"

artifacts-change:
  - changed-files:
      - any-glob-to-any-file: "artifacts.json"

build:
  - changed-files:
      - any-glob-to-any-file: "build-logic/**"
      - any-glob-to-any-file: "gradle/**"
      - any-glob-to-any-file: "**/gradle.properties"

ci:
  - changed-files:
      - any-glob-to-any-file: ".github/**"

classpath-change:
  - changed-files:
      - any-glob-to-any-file: "**/dependencies/*Classpath.txt"

dependencies:
  - changed-files:
      - any-glob-to-any-file: "gradle/libs.versions.toml"

documentation:
  - changed-files:
      - any-glob-to-any-file: "**/*.md"
      - any-glob-to-any-file: "**/*.mdx"

website:
  - changed-files:
      - any-glob-to-any-file: "website/**"
