name: CI

on:
  pull_request:
  merge_group:
  workflow_dispatch:

env:
  macosGradleArgs: "-Dorg.gradle.jvmargs=-Xmx10g -Dfile.encoding=UTF-8 -XX:+UseParallelGC"
  ubuntuGradleArgs: "-Dorg.gradle.jvmargs=-Xmx5g -Dfile.encoding=UTF-8 -XX:+UseParallelGC"
  windowsGradleArgs: "-Dorg.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8 -XX:+UseParallelGC"

jobs:
  cancel-previous-runs:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.0
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: check out with token (used by forks)
        uses: actions/checkout@v4
        if: github.event.repository.fork == true

      - name: check out with PAT (used by main repo)
        uses: actions/checkout@v4
        if: github.event.repository.fork == false
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"

      - name: dependency-guard baseline (used by main repo)
        if: github.event.repository.fork == false
        uses: gradle/gradle-build-action@v2
        with:
          arguments: dependencyGuardBaseline
          cache-read-only: false --refresh-dependencies

      # If the baseline was just updated, commit and push those changes.
      - name: commit dependency-guard baseline changes (used by main repo)
        if: github.event.repository.fork == false
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: update dependency-guard baseline
          commit_options: "--no-verify --signoff"

      - name: dependency-guard check (used by forks)
        if: github.event.repository.fork == true
        uses: gradle/gradle-build-action@v2
        with:
          arguments: dependencyGuard
          cache-read-only: false --refresh-dependencies

      - name: curator check
        uses: gradle/gradle-build-action@v2
        with:
          arguments: curatorCheck
          cache-read-only: false

      - name: detekt
        uses: gradle/gradle-build-action@v2
        with:
          arguments: detektAll
          cache-read-only: false

      - name: merge detekt SARIF reports
        uses: gradle/gradle-build-action@v2
        with:
          arguments: detektReportMerge
          cache-read-only: false

      - name: Upload Detekt's SARIF report
        uses: github/codeql-action/upload-sarif@v3
        if: failure()
        with:
          sarif_file: build/reports/detekt/merged.sarif

      - name: KtLint format (used by main repo)
        if: github.event.repository.fork == false
        uses: gradle/gradle-build-action@v2
        with:
          arguments: ktlintFormat
          cache-read-only: false

      # If KtLint generated changes, commit and push those changes.
      - name: commit changes (used by main repo)
        if: github.event.repository.fork == false
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Apply KtLint format
          commit_options: "--no-verify --signoff"

      - name: KtLint check (used by forks)
        if: github.event.repository.fork == true
        uses: gradle/gradle-build-action@v2
        with:
          arguments: ktlintCheck
          cache-read-only: false

      - name: Doks update (used by main repo)
        if: github.event.repository.fork == false
        uses: gradle/gradle-build-action@v2
        with:
          arguments: doks
          cache-read-only: false

      # If Doks generated changes, commit and push those changes.
      - name: commit changes (used by main repo)
        if: github.event.repository.fork == false
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Apply Doks updates
          commit_options: "--no-verify --signoff"

      - name: Doks check (used by forks)
        if: github.event.repository.fork == true
        uses: gradle/gradle-build-action@v2
        with:
          arguments: doksCheck
          cache-read-only: false

      - name: ModuleCheck with auto-correct (used by main repo)
        if: github.event.repository.fork == false
        uses: gradle/gradle-build-action@v2
        with:
          arguments: moduleCheckAuto
          cache-read-only: false

      # If ModuleCheck generated changes, commit and push those changes.
      - name: commit changes (used by main repo)
        if: github.event.repository.fork == false
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Apply ModuleCheck fixes
          commit_options: "--no-verify --signoff"

      - name: ModuleCheck check (used by forks)
        if: github.event.repository.fork == true
        uses: gradle/gradle-build-action@v2
        with:
          arguments: moduleCheck
          cache-read-only: false

  tests-macos:
    runs-on: ubuntu-latest

    steps:
      - name: check out with token
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"

      - name: all tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test "${{ env.ubuntuGradleArgs }}"
          cache-read-only: false

      - name: Archive test results
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: test-results-ubuntu
          path: ./**/build/reports/tests/test

      - name: Unit test results
        uses: mikepenz/action-junit-report@v4
        if: failure()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          report_paths: "**/build/**/TEST-*.xml"
          check_name: Unit Test Results - ubuntu

  integration-tests-macos:
    runs-on: ubuntu-latest

    steps:
      - name: check out with token
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"

      - name: all integration tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test "${{ env.ubuntuGradleArgs }}"
          cache-read-only: false

      - name: Archive test results
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: test-results-ubuntu
          path: ./**/build/reports/tests/integrationTest

      - name: Unit test results
        uses: mikepenz/action-junit-report@v4
        if: failure()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          report_paths: "**/build/**/TEST-*.xml"
          check_name: Unit Test Results - ubuntu

  tests-windows:
    runs-on: windows-latest

    steps:
      - name: check out with token
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"

      - name: all tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test "${{ env.windowsGradleArgs }}"
          cache-read-only: false

      - name: Archive test results
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: test-results-windows
          path: ./**/build/reports/tests/

      - name: Unit test results
        uses: mikepenz/action-junit-report@v4
        if: failure()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          report_paths: "**/build/**/TEST-*.xml"
          check_name: Unit Test Results - Windows

  all-green:
    if: always()
    runs-on: ubuntu-latest
    needs:
      - integration-tests-macos
      - static-analysis
      - tests-macos
      - tests-windows

    steps:
      - name: require that all other jobs have passed
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
